import { Preset } from '../types';

export const DEFAULT_PRESETS: Preset[] = [
  {
    id: 'modern_wave',
    name: 'Onda Orgánica',
    description: 'Cuadrícula con ondas suaves y fluidas que simulan el movimiento del agua o la tela.',
    settings: {
      cols: 42,
      rows: 42,
      strokeWidth: 1.2,
      showPoints: false,
      pointSize: 2,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      distortionType: 'sine',
      amplitude: 28,
      frequency: 0.15,
      edgeFalloff: 0.8,
      interactionMode: 'repel',
      interactionRadius: 180,
      interactionStrength: 1.2,
      persistDisplacement: false,
      elasticity: 0.08,
      animate: true,
      animationSpeed: 1.2,
      paperTexture: true,
      colorInverted: false
    }
  },
  {
    id: 'origami_fold',
    name: 'Pliegues Origami',
    description: 'Líneas nítidas triangulares que recuerdan al papel doblado con precisión geométrica.',
    settings: {
      cols: 28,
      rows: 28,
      strokeWidth: 1.0,
      showPoints: false,
      pointSize: 2,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'left',
      distortionType: 'fold',
      amplitude: 35,
      frequency: 0.22,
      edgeFalloff: 0.9,
      interactionMode: 'vortex',
      interactionRadius: 150,
      interactionStrength: 1.5,
      persistDisplacement: false,
      elasticity: 0.05,
      animate: false,
      animationSpeed: 0.8,
      paperTexture: true,
      colorInverted: false
    }
  },
  {
    id: 'vortex_warp',
    name: 'Tornado / Vórtice',
    description: 'Un espiral hipnótico de celdas que giran alrededor del centro de la pantalla.',
    settings: {
      cols: 35,
      rows: 35,
      strokeWidth: 1.1,
      showPoints: true,
      pointSize: 1.5,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      distortionType: 'vortex',
      amplitude: 70,
      frequency: 0.12,
      edgeFalloff: 0.5,
      interactionMode: 'attract',
      interactionRadius: 200,
      interactionStrength: 1.0,
      persistDisplacement: false,
      elasticity: 0.07,
      animate: true,
      animationSpeed: 0.6,
      paperTexture: false,
      colorInverted: false
    }
  },
  {
    id: 'clay_sculpt',
    name: 'Escultura de Arcilla',
    description: 'Cuadrícula perfectamente limpia lista para ser esculpida con el cursor. Arrastra para deformar permanentemente.',
    settings: {
      cols: 30,
      rows: 30,
      strokeWidth: 1.5,
      showPoints: false,
      pointSize: 3,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      distortionType: 'sine',
      amplitude: 0,
      frequency: 0.1,
      edgeFalloff: 0.7,
      interactionMode: 'smudge',
      interactionRadius: 160,
      interactionStrength: 2.0,
      persistDisplacement: true,
      elasticity: 0.12,
      animate: false,
      animationSpeed: 1.0,
      paperTexture: true,
      colorInverted: false
    }
  },
  {
    id: 'cosmic_matrix',
    name: 'Matriz de Ruido',
    description: 'Una red ultra densa que muestra la belleza aleatoria del campo fractal matemático.',
    settings: {
      cols: 64,
      rows: 64,
      strokeWidth: 0.7,
      showPoints: false,
      pointSize: 1,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      distortionType: 'noise',
      amplitude: 45,
      frequency: 0.25,
      edgeFalloff: 0.95,
      interactionMode: 'repel',
      interactionRadius: 220,
      interactionStrength: 1.6,
      persistDisplacement: false,
      elasticity: 0.06,
      animate: true,
      animationSpeed: 0.8,
      paperTexture: true,
      colorInverted: false
    }
  },
  {
    id: 'minimal_bold',
    name: 'Puro Minimalismo',
    description: 'Una cuadrícula gruesa y austera de alto impacto gráfico inspirado en el diseño editorial suizo.',
    settings: {
      cols: 12,
      rows: 12,
      strokeWidth: 4.5,
      showPoints: true,
      pointSize: 6,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      distortionType: 'sine',
      amplitude: 15,
      frequency: 0.08,
      edgeFalloff: 0.3,
      interactionMode: 'smudge',
      interactionRadius: 180,
      interactionStrength: 1.5,
      persistDisplacement: false,
      elasticity: 0.15,
      animate: false,
      animationSpeed: 1.0,
      paperTexture: true,
      colorInverted: false
    }
  }
];
