import { Preset } from '../types';

export const DEFAULT_PRESETS: Preset[] = [
  {
    id: 'modern_wave',
    name: 'Onda Orgánica',
    description: 'Cuadrícula con ondas suaves y fluidas que simulan el movimiento del agua o la tela.',
    settings: {
      cols: 30,
      rows: 30,
      strokeWidth: 1.2,
      showPoints: false,
      pointSize: 2,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      renderMode: 'lines',
      customText: 'sappy',
      textSize: 12,
      distortionType: 'sine',
      amplitude: 28,
      frequency: 0.15,
      edgeFalloff: 0.8,
      interactionMode: 'repel',
      interactionRadius: 180,
      interactionStrength: 1.2,
      persistDisplacement: false,
      elasticity: 0.08,
      animate: true,
      animationSpeed: 1.2,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'puntos_puros',
    name: 'Constelación de Nodos',
    description: 'Un lienzo limpio sin líneas, compuesto únicamente por puntos interactivos flotantes.',
    settings: {
      cols: 24,
      rows: 24,
      strokeWidth: 0,
      showPoints: true,
      pointSize: 3.5,
      showVerticalLines: false,
      showHorizontalLines: false,
      diagonalLines: 'none',
      renderMode: 'points',
      customText: 'sappy',
      textSize: 12,
      distortionType: 'composition_marble',
      amplitude: 30,
      frequency: 0.2,
      edgeFalloff: 0.6,
      interactionMode: 'repel',
      interactionRadius: 150,
      interactionStrength: 1.4,
      persistDisplacement: false,
      elasticity: 0.09,
      animate: true,
      animationSpeed: 1.0,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'texto_generativo',
    name: 'Texto s.e',
    description: 'Un patrón tipográfico dinámico que se deforma y reacciona de forma elástica a tus gestos.',
    settings: {
      cols: 22,
      rows: 22,
      strokeWidth: 1.0,
      showPoints: false,
      pointSize: 2,
      showVerticalLines: false,
      showHorizontalLines: false,
      diagonalLines: 'none',
      renderMode: 'text',
      customText: 'sappy.error',
      textSize: 11,
      distortionType: 'neural',
      amplitude: 35,
      frequency: 0.18,
      edgeFalloff: 0.8,
      interactionMode: 'vortex',
      interactionRadius: 160,
      interactionStrength: 1.5,
      persistDisplacement: false,
      elasticity: 0.07,
      animate: true,
      animationSpeed: 1.0,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'origami_fold',
    name: 'Pliegues Origami',
    description: 'Líneas nítidas triangulares que recuerdan al papel doblado con precisión geométrica.',
    settings: {
      cols: 20,
      rows: 20,
      strokeWidth: 1.0,
      showPoints: false,
      pointSize: 2,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'left',
      renderMode: 'lines',
      customText: 'sappy',
      textSize: 12,
      distortionType: 'fold',
      amplitude: 35,
      frequency: 0.22,
      edgeFalloff: 0.9,
      interactionMode: 'vortex',
      interactionRadius: 150,
      interactionStrength: 1.5,
      persistDisplacement: false,
      elasticity: 0.05,
      animate: false,
      animationSpeed: 0.8,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'vortex_warp',
    name: 'Tornado / Vórtice',
    description: 'Un espiral hipnótico de celdas que giran alrededor del centro de la pantalla.',
    settings: {
      cols: 26,
      rows: 26,
      strokeWidth: 1.1,
      showPoints: true,
      pointSize: 1.5,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      renderMode: 'lines',
      customText: 'sappy',
      textSize: 12,
      distortionType: 'vortex',
      amplitude: 70,
      frequency: 0.12,
      edgeFalloff: 0.5,
      interactionMode: 'attract',
      interactionRadius: 200,
      interactionStrength: 1.0,
      persistDisplacement: false,
      elasticity: 0.07,
      animate: true,
      animationSpeed: 0.6,
      paperTexture: false,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'clay_sculpt',
    name: 'Escultura de Arcilla',
    description: 'Cuadrícula perfectamente limpia lista para ser esculpida con el cursor. Arrastra para deformar permanentemente.',
    settings: {
      cols: 22,
      rows: 22,
      strokeWidth: 1.5,
      showPoints: false,
      pointSize: 3,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      renderMode: 'lines',
      customText: 'sappy',
      textSize: 12,
      distortionType: 'sine',
      amplitude: 0,
      frequency: 0.1,
      edgeFalloff: 0.7,
      interactionMode: 'smudge',
      interactionRadius: 160,
      interactionStrength: 2.0,
      persistDisplacement: true,
      elasticity: 0.12,
      animate: false,
      animationSpeed: 1.0,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'cosmic_matrix',
    name: 'Matriz de Ruido',
    description: 'Una red ultra densa que muestra la belleza aleatoria del campo fractal matemático.',
    settings: {
      cols: 38,
      rows: 38,
      strokeWidth: 0.7,
      showPoints: false,
      pointSize: 1,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      renderMode: 'lines',
      customText: 'sappy',
      textSize: 12,
      distortionType: 'noise',
      amplitude: 45,
      frequency: 0.25,
      edgeFalloff: 0.95,
      interactionMode: 'repel',
      interactionRadius: 220,
      interactionStrength: 1.6,
      persistDisplacement: false,
      elasticity: 0.06,
      animate: true,
      animationSpeed: 0.8,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'minimal_bold',
    name: 'Puro Minimalismo',
    description: 'Una cuadrícula gruesa y austera de alto impacto gráfico inspirado en el diseño editorial suizo.',
    settings: {
      cols: 9,
      rows: 9,
      strokeWidth: 4.5,
      showPoints: true,
      pointSize: 6,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      renderMode: 'lines',
      customText: 'sappy',
      textSize: 12,
      distortionType: 'sine',
      amplitude: 15,
      frequency: 0.08,
      edgeFalloff: 0.3,
      interactionMode: 'smudge',
      interactionRadius: 180,
      interactionStrength: 1.5,
      persistDisplacement: false,
      elasticity: 0.15,
      animate: false,
      animationSpeed: 1.0,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'cad_urban_flow',
    name: 'Escala Humana (CAD)',
    description: 'Vistas en planta de personas que fluyen y giran dinámicamente según la corriente del viento o interacciones con el cursor.',
    settings: {
      cols: 14,
      rows: 14,
      strokeWidth: 1.0,
      showPoints: false,
      pointSize: 10,
      showVerticalLines: false,
      showHorizontalLines: false,
      diagonalLines: 'none',
      renderMode: 'cad-people',
      customText: 'CAD',
      textSize: 12,
      distortionType: 'wind_currents',
      amplitude: 45,
      frequency: 0.12,
      edgeFalloff: 0.7,
      interactionMode: 'repel',
      interactionRadius: 160,
      interactionStrength: 1.6,
      persistDisplacement: false,
      elasticity: 0.08,
      animate: true,
      animationSpeed: 1.0,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'nature_wind_gusts',
    name: 'Corrientes de Viento',
    description: 'Líneas densas y continuas que se deforman con ráfagas y remolinos que imitan la física atmosférica.',
    settings: {
      cols: 32,
      rows: 32,
      strokeWidth: 0.9,
      showPoints: false,
      pointSize: 2,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      renderMode: 'lines',
      customText: '',
      textSize: 12,
      distortionType: 'wind_currents',
      amplitude: 50,
      frequency: 0.18,
      edgeFalloff: 0.85,
      interactionMode: 'vortex',
      interactionRadius: 180,
      interactionStrength: 1.3,
      persistDisplacement: false,
      elasticity: 0.07,
      animate: true,
      animationSpeed: 1.3,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'nature_points_drift',
    name: 'Polen Orgánico',
    description: 'Nodos flotantes de alta densidad que se desplazan como partículas suspendidas en un río de viento.',
    settings: {
      cols: 28,
      rows: 28,
      strokeWidth: 1.0,
      showPoints: true,
      pointSize: 3,
      showVerticalLines: false,
      showHorizontalLines: false,
      diagonalLines: 'none',
      renderMode: 'points',
      customText: '',
      textSize: 12,
      distortionType: 'growing_mountains',
      amplitude: 60,
      frequency: 0.15,
      edgeFalloff: 0.6,
      interactionMode: 'repel',
      interactionRadius: 150,
      interactionStrength: 1.8,
      persistDisplacement: false,
      elasticity: 0.1,
      animate: true,
      animationSpeed: 1.1,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'nature_typographic_forest',
    name: 'Bosque de Letras',
    description: 'Un patrón tipográfico poético e interactivo que se deforma con el movimiento de tu cursor.',
    settings: {
      cols: 22,
      rows: 22,
      strokeWidth: 1.0,
      showPoints: false,
      pointSize: 4,
      showVerticalLines: false,
      showHorizontalLines: false,
      diagonalLines: 'none',
      renderMode: 'text',
      customText: 'NATURALEZA',
      textSize: 11,
      distortionType: 'river_flow',
      amplitude: 40,
      frequency: 0.1,
      edgeFalloff: 0.5,
      interactionMode: 'attract',
      interactionRadius: 200,
      interactionStrength: 1.5,
      persistDisplacement: false,
      elasticity: 0.08,
      animate: true,
      animationSpeed: 1.0,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'matrix_digital_nature',
    name: 'Flujo Binario (ASCII)',
    description: 'Símbolos de consola, variables lógicas y operadores matriciales que giran alineados al campo de fuerza.',
    settings: {
      cols: 24,
      rows: 24,
      strokeWidth: 1.0,
      showPoints: false,
      pointSize: 4,
      showVerticalLines: false,
      showHorizontalLines: false,
      diagonalLines: 'none',
      renderMode: 'ascii',
      customText: '',
      textSize: 9,
      distortionType: 'neural',
      amplitude: 55,
      frequency: 0.14,
      edgeFalloff: 0.4,
      interactionMode: 'vortex',
      interactionRadius: 180,
      interactionStrength: 2.0,
      persistDisplacement: false,
      elasticity: 0.06,
      animate: true,
      animationSpeed: 1.2,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'escher_stairs_preset',
    name: 'Escaleras Escher',
    description: 'Estructura geométrica e isométrica de peldaños entrelazados que simulan perspectivas imposibles e infinitas.',
    settings: {
      cols: 25,
      rows: 25,
      strokeWidth: 1.5,
      showPoints: false,
      pointSize: 2,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'both',
      renderMode: 'lines',
      customText: '',
      textSize: 12,
      distortionType: 'escher_stairs',
      amplitude: 35,
      frequency: 0.15,
      edgeFalloff: 0.8,
      interactionMode: 'vortex',
      interactionRadius: 180,
      interactionStrength: 1.4,
      persistDisplacement: false,
      elasticity: 0.08,
      animate: true,
      animationSpeed: 0.6,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'cross_stitch_preset',
    name: 'Punto de Cruz',
    description: 'Un patrón bordado artesanal donde cada coordenada se divide en cruces (X) diagonales y simétricas.',
    settings: {
      cols: 24,
      rows: 24,
      strokeWidth: 1.8,
      showPoints: false,
      pointSize: 2,
      showVerticalLines: false,
      showHorizontalLines: false,
      diagonalLines: 'both',
      renderMode: 'lines',
      customText: '',
      textSize: 12,
      distortionType: 'cross_stitch',
      amplitude: 22,
      frequency: 0.2,
      edgeFalloff: 0.7,
      interactionMode: 'repel',
      interactionRadius: 140,
      interactionStrength: 1.5,
      persistDisplacement: false,
      elasticity: 0.1,
      animate: true,
      animationSpeed: 0.8,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'growing_mountains_preset',
    name: 'Montañas Dinámicas',
    description: 'Líneas horizontales superpuestas que se elevan y forman cordilleras dinámicas con valles y crestas de relieve.',
    settings: {
      cols: 35,
      rows: 22,
      strokeWidth: 1.4,
      showPoints: false,
      pointSize: 2,
      showVerticalLines: false,
      showHorizontalLines: true,
      diagonalLines: 'none',
      renderMode: 'lines',
      customText: '',
      textSize: 12,
      distortionType: 'growing_mountains',
      amplitude: 45,
      frequency: 0.18,
      edgeFalloff: 0.9,
      interactionMode: 'attract',
      interactionRadius: 180,
      interactionStrength: 1.2,
      persistDisplacement: false,
      elasticity: 0.07,
      animate: true,
      animationSpeed: 0.7,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'composition_marble_preset',
    name: 'Mármol Líquido',
    description: 'Remolinos orgánicos ultra densos inspirados en las texturas de papel veteado y portadas de cuadernos de composición.',
    settings: {
      cols: 42,
      rows: 42,
      strokeWidth: 0.75,
      showPoints: false,
      pointSize: 1,
      showVerticalLines: true,
      showHorizontalLines: true,
      diagonalLines: 'none',
      renderMode: 'lines',
      customText: '',
      textSize: 12,
      distortionType: 'composition_marble',
      amplitude: 55,
      frequency: 0.22,
      edgeFalloff: 0.8,
      interactionMode: 'vortex',
      interactionRadius: 200,
      interactionStrength: 1.6,
      persistDisplacement: false,
      elasticity: 0.05,
      animate: true,
      animationSpeed: 0.9,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'sonya_rapoport_preset',
    name: 'Sonya Rapoport (Plóter)',
    description: 'Inspirado en la histórica obra de arte computacional "Shoe-Field". Trama de datos de densidades tipográficas, números y símbolos acumulados.',
    settings: {
      cols: 32,
      rows: 32,
      strokeWidth: 1,
      showPoints: false,
      pointSize: 1,
      showVerticalLines: false,
      showHorizontalLines: false,
      diagonalLines: 'none',
      renderMode: 'ascii',
      asciiCharacterSet: 'sonya',
      customText: '',
      textSize: 9,
      distortionType: 'mixed',
      amplitude: 35,
      frequency: 0.15,
      edgeFalloff: 0.75,
      interactionMode: 'repel',
      interactionRadius: 160,
      interactionStrength: 1.5,
      persistDisplacement: false,
      elasticity: 0.08,
      animate: true,
      animationSpeed: 0.5,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  },
  {
    id: 'halftone_raster_preset',
    name: 'Grabado Puntillista',
    description: 'Trama de puntos mecánicos de densidad variable que componen un grabado dithered interactivo.',
    settings: {
      cols: 38,
      rows: 38,
      strokeWidth: 1,
      showPoints: false,
      pointSize: 1,
      showVerticalLines: false,
      showHorizontalLines: false,
      diagonalLines: 'none',
      renderMode: 'ascii',
      asciiCharacterSet: 'grayscale_dots',
      customText: '',
      textSize: 10,
      distortionType: 'noise',
      amplitude: 40,
      frequency: 0.2,
      edgeFalloff: 0.8,
      interactionMode: 'vortex',
      interactionRadius: 180,
      interactionStrength: 1.4,
      persistDisplacement: false,
      elasticity: 0.08,
      animate: true,
      animationSpeed: 0.7,
      paperTexture: true,
      colorInverted: false,
      includeSignature: true
    }
  }
];

